// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG7GyX5ksFpgBmX8cG0XrQbCpi25ReHMU',
    appId: '1:332828351511:web:97f88af8faa86623d9d052',
    messagingSenderId: '332828351511',
    projectId: 'chat-app-3bf61',
    authDomain: 'chat-app-3bf61.firebaseapp.com',
    storageBucket: 'chat-app-3bf61.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPFSiFX0qA0DyIBq043rrdWC7ddUg_s7k',
    appId: '1:332828351511:android:1cdb7a15b30a4731d9d052',
    messagingSenderId: '332828351511',
    projectId: 'chat-app-3bf61',
    storageBucket: 'chat-app-3bf61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWpF9vWa9xqmee9Q1x6H71TekAl8m2QNo',
    appId: '1:332828351511:ios:1b6ac0a6705fca26d9d052',
    messagingSenderId: '332828351511',
    projectId: 'chat-app-3bf61',
    storageBucket: 'chat-app-3bf61.appspot.com',
    iosClientId: '332828351511-e15rnds1lf4b4k2qojk07i7t1p3i5u38.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWpF9vWa9xqmee9Q1x6H71TekAl8m2QNo',
    appId: '1:332828351511:ios:1b6ac0a6705fca26d9d052',
    messagingSenderId: '332828351511',
    projectId: 'chat-app-3bf61',
    storageBucket: 'chat-app-3bf61.appspot.com',
    iosClientId: '332828351511-e15rnds1lf4b4k2qojk07i7t1p3i5u38.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
